export const skillUpgradeData = [
  {
    skill_id: 1,
    skill_name: "React.js",
    from_level: 1,
    to_level: 2,
    plan: "Start by completing the beginner module on freeCodeCamp, then build a small project using what you learned.",
    resources:
      "https://www.freecodecamp.org/learn/front-end-development-libraries/react/",
  },
  {
    skill_id: 1,
    skill_name: "React.js",
    from_level: 1,
    to_level: 3,
    plan: "Complete the intermediate module on freeCodeCamp, then create a more complex project using React hooks.",
    resources:
      "https://www.freecodecamp.org/learn/front-end-development-libraries/react/",
  },
  {
    skill_id: 1,
    skill_name: "React.js",
    from_level: 1,
    to_level: 4,
    plan: "Finish the advanced module on freeCodeCamp, then contribute to an open-source React project.",
    resources:
      "https://www.freecodecamp.org/learn/front-end-development-libraries/react/",
  },
  {
    skill_id: 1,
    skill_name: "React.js",
    from_level: 2,
    to_level: 3,
    plan: "Build a medium-sized project using React hooks and context API, then read advanced React patterns.",
    resources: "https://reactjs.org/docs/hooks-intro.html",
  },
  {
    skill_id: 1,
    skill_name: "React.js",
    from_level: 2,
    to_level: 4,
    plan: "Create a large-scale project focusing on performance optimization, then study React's source code.",
    resources: "https://reactjs.org/docs/optimizing-performance.html",
  },
  {
    skill_id: 1,
    skill_name: "React.js",
    from_level: 3,
    to_level: 4,
    plan: "Contribute to an open-source React project, then write articles or tutorials on advanced React topics.",
    resources: "https://reactjs.org/community/support.html",
  },
  {
    skill_id: 2,
    skill_name: "Vue.js",
    from_level: 1,
    to_level: 2,
    plan: "Start with the Vue.js guide on the official website, then build a simple project using Vue CLI.",
    resources: "https://vuejs.org/v2/guide/",
  },
  {
    skill_id: 2,
    skill_name: "Vue.js",
    from_level: 1,
    to_level: 3,
    plan: "Complete the Vue Mastery beginner course, then create a project using Vue Router and Vuex.",
    resources:
      "https://www.vuemastery.com/courses/intro-to-vue-3/intro-to-vue3/",
  },
  {
    skill_id: 2,
    skill_name: "Vue.js",
    from_level: 1,
    to_level: 4,
    plan: "Finish the Vue Mastery advanced course, then contribute to an open-source Vue.js project.",
    resources: "https://www.vuemastery.com/courses/advanced-vue/",
  },
  {
    skill_id: 2,
    skill_name: "Vue.js",
    from_level: 2,
    to_level: 3,
    plan: "Build a medium-sized project using Vue Router and Vuex, then read advanced Vue.js patterns.",
    resources: "https://vuejs.org/v2/guide/routing.html",
  },
  {
    skill_id: 2,
    skill_name: "Vue.js",
    from_level: 2,
    to_level: 4,
    plan: "Create a large-scale project focusing on performance optimization, then study Vue.js source code.",
    resources: "https://vuejs.org/v2/guide/optimizing-performance.html",
  },
  {
    skill_id: 2,
    skill_name: "Vue.js",
    from_level: 3,
    to_level: 4,
    plan: "Contribute to an open-source Vue.js project, then write articles or tutorials on advanced Vue.js topics.",
    resources: "https://vuejs.org/v2/community/",
  },
  {
    skill_id: 3,
    skill_name: "HTML5",
    from_level: 1,
    to_level: 2,
    plan: "Start with the HTML5 tutorial on MDN, then build a simple webpage using HTML5 elements.",
    resources: "https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5",
  },
  {
    skill_id: 3,
    skill_name: "HTML5",
    from_level: 1,
    to_level: 3,
    plan: "Complete the HTML5 course on freeCodeCamp, then create a project focusing on semantic HTML.",
    resources: "https://www.freecodecamp.org/learn/responsive-web-design/",
  },
  {
    skill_id: 3,
    skill_name: "HTML5",
    from_level: 1,
    to_level: 4,
    plan: "Finish the advanced HTML5 tutorial on MDN, then contribute to an open-source HTML5 project.",
    resources: "https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5",
  },
  {
    skill_id: 3,
    skill_name: "HTML5",
    from_level: 2,
    to_level: 3,
    plan: "Build a medium-sized project using semantic HTML, then read advanced HTML5 patterns.",
    resources: "https://developer.mozilla.org/en-US/docs/Web/HTML",
  },
  {
    skill_id: 3,
    skill_name: "HTML5",
    from_level: 2,
    to_level: 4,
    plan: "Create a large-scale project focusing on accessibility, then study HTML5 APIs.",
    resources: "https://developer.mozilla.org/en-US/docs/Web/API",
  },
  {
    skill_id: 3,
    skill_name: "HTML5",
    from_level: 3,
    to_level: 4,
    plan: "Contribute to an open-source HTML5 project, then write articles or tutorials on advanced HTML5 topics.",
    resources: "https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5",
  },
  {
    skill_id: 4,
    skill_name: "CSS3",
    from_level: 1,
    to_level: 2,
    plan: "Start with the CSS3 tutorial on MDN, then build a simple webpage using CSS3 properties.",
    resources: "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS3",
  },
  {
    skill_id: 4,
    skill_name: "CSS3",
    from_level: 1,
    to_level: 3,
    plan: "Complete the CSS3 course on freeCodeCamp, then create a project focusing on Flexbox and Grid.",
    resources: "https://www.freecodecamp.org/learn/responsive-web-design/",
  },
  {
    skill_id: 4,
    skill_name: "CSS3",
    from_level: 1,
    to_level: 4,
    plan: "Finish the advanced CSS3 tutorial on MDN, then contribute to an open-source CSS3 project.",
    resources: "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS3",
  },
  {
    skill_id: 4,
    skill_name: "CSS3",
    from_level: 2,
    to_level: 3,
    plan: "Build a medium-sized project using Flexbox and Grid, then read advanced CSS3 patterns.",
    resources:
      "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout",
  },
  {
    skill_id: 4,
    skill_name: "CSS3",
    from_level: 2,
    to_level: 4,
    plan: "Create a large-scale project focusing on animations and transitions, then study CSS preprocessors.",
    resources:
      "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations",
  },
  {
    skill_id: 4,
    skill_name: "CSS3",
    from_level: 3,
    to_level: 4,
    plan: "Contribute to an open-source CSS3 project, then write articles or tutorials on advanced CSS3 topics.",
    resources: "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS3",
  },
  {
    skill_id: 5,
    skill_name: "JavaScript",
    from_level: 1,
    to_level: 2,
    plan: "Start with the JavaScript tutorial on MDN, then build a simple project using basic JavaScript.",
    resources: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
  },
  {
    skill_id: 5,
    skill_name: "JavaScript",
    from_level: 1,
    to_level: 3,
    plan: "Complete the JavaScript course on freeCodeCamp, then create a project focusing on ES6 features.",
    resources:
      "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/",
  },
  {
    skill_id: 5,
    skill_name: "JavaScript",
    from_level: 1,
    to_level: 4,
    plan: "Finish the advanced JavaScript tutorial on MDN, then contribute to an open-source JavaScript project.",
    resources: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
  },
  {
    skill_id: 5,
    skill_name: "JavaScript",
    from_level: 2,
    to_level: 3,
    plan: "Build a medium-sized project using ES6 features, then read advanced JavaScript patterns.",
    resources: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  },
  {
    skill_id: 5,
    skill_name: "JavaScript",
    from_level: 2,
    to_level: 4,
    plan: "Create a large-scale project focusing on async programming, then study JavaScript design patterns.",
    resources:
      "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises",
  },
  {
    skill_id: 5,
    skill_name: "JavaScript",
    from_level: 3,
    to_level: 4,
    plan: "Contribute to an open-source JavaScript project, then write articles or tutorials on advanced JavaScript topics.",
    resources: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
  },

  {
    skill_id: 6,
    skill_name: "Node.js",
    from_level: 1,
    to_level: 2,
    plan: "Start by learning the basics of Node.js from the official documentation, then build a simple CLI tool.",
    resources: "https://nodejs.dev/en/learn/",
  },
  {
    skill_id: 6,
    skill_name: "Node.js",
    from_level: 1,
    to_level: 3,
    plan: "Complete the Node.js course on freeCodeCamp and build a REST API using Express.",
    resources: "https://www.freecodecamp.org/news/learn-node-js-full-course/",
  },
  {
    skill_id: 6,
    skill_name: "Node.js",
    from_level: 1,
    to_level: 4,
    plan: "Take an advanced Node.js course and deploy a full-stack app using Node and MongoDB.",
    resources:
      "https://www.udemy.com/course/the-complete-nodejs-developer-course-2/",
  },
  {
    skill_id: 6,
    skill_name: "Node.js",
    from_level: 2,
    to_level: 3,
    plan: "Build a mid-sized project using Express and middleware, then explore asynchronous patterns.",
    resources: "https://expressjs.com/en/starter/installing.html",
  },
  {
    skill_id: 6,
    skill_name: "Node.js",
    from_level: 2,
    to_level: 4,
    plan: "Create a scalable backend with clustering and load balancing, then integrate with a database.",
    resources: "https://nodejs.org/en/docs/guides/",
  },
  {
    skill_id: 6,
    skill_name: "Node.js",
    from_level: 3,
    to_level: 4,
    plan: "Contribute to an open-source Node.js project and write technical blogs on performance tuning.",
    resources: "https://github.com/nodejs/node",
  },
  {
    skill_id: 7,
    skill_name: "Express.js",
    from_level: 1,
    to_level: 2,
    plan: "Read the Express.js getting started guide and build a basic server with routes.",
    resources: "https://expressjs.com/en/starter/installing.html",
  },
  {
    skill_id: 7,
    skill_name: "Express.js",
    from_level: 1,
    to_level: 3,
    plan: "Follow a tutorial to build a RESTful API with Express and test it using Postman.",
    resources:
      "https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs",
  },
  {
    skill_id: 7,
    skill_name: "Express.js",
    from_level: 1,
    to_level: 4,
    plan: "Take an advanced Express.js course and implement authentication and error handling.",
    resources: "https://www.udemy.com/course/nodejs-express-mongodb-bootcamp/",
  },
  {
    skill_id: 7,
    skill_name: "Express.js",
    from_level: 2,
    to_level: 3,
    plan: "Build a project with Express middleware and routing, then integrate with MongoDB.",
    resources: "https://www.mongodb.com/languages/express",
  },
  {
    skill_id: 7,
    skill_name: "Express.js",
    from_level: 2,
    to_level: 4,
    plan: "Create a production-ready API with logging, validation, and security best practices.",
    resources:
      "https://expressjs.com/en/advanced/best-practice-performance.html",
  },
  {
    skill_id: 7,
    skill_name: "Express.js",
    from_level: 3,
    to_level: 4,
    plan: "Contribute to Express.js GitHub issues and write middleware for community use.",
    resources: "https://github.com/expressjs/express",
  },
  {
    skill_id: 8,
    skill_name: "MongoDB",
    from_level: 1,
    to_level: 2,
    plan: "Start with MongoDB University’s basics course and practice CRUD operations.",
    resources: "https://university.mongodb.com/courses/M001/about",
  },
  {
    skill_id: 8,
    skill_name: "MongoDB",
    from_level: 1,
    to_level: 3,
    plan: "Build a Node.js app with MongoDB and explore schema design and indexing.",
    resources: "https://www.mongodb.com/languages/mern-stack-tutorial",
  },
  {
    skill_id: 8,
    skill_name: "MongoDB",
    from_level: 1,
    to_level: 4,
    plan: "Take an advanced MongoDB course and implement aggregation pipelines and transactions.",
    resources: "https://university.mongodb.com/courses/M121/about",
  },
  {
    skill_id: 8,
    skill_name: "MongoDB",
    from_level: 2,
    to_level: 3,
    plan: "Design a schema for a real-world app and optimize queries using indexes.",
    resources: "https://www.mongodb.com/docs/manual/indexes/",
  },
  {
    skill_id: 8,
    skill_name: "MongoDB",
    from_level: 2,
    to_level: 4,
    plan: "Implement replication and sharding in a test environment and monitor performance.",
    resources: "https://www.mongodb.com/docs/manual/replication/",
  },
  {
    skill_id: 8,
    skill_name: "MongoDB",
    from_level: 3,
    to_level: 4,
    plan: "Contribute to MongoDB open-source tools and write a blog on performance tuning.",
    resources: "https://github.com/mongodb",
  },
  {
    skill_id: 9,
    skill_name: "PostgreSQL",
    from_level: 1,
    to_level: 2,
    plan: "Learn SQL basics using PostgreSQL and practice with SELECT, INSERT, and UPDATE queries.",
    resources: "https://www.postgresqltutorial.com/",
  },
  {
    skill_id: 9,
    skill_name: "PostgreSQL",
    from_level: 1,
    to_level: 3,
    plan: "Build a database-driven app and explore joins, constraints, and normalization.",
    resources: "https://www.codecademy.com/learn/learn-sql",
  },
  {
    skill_id: 9,
    skill_name: "PostgreSQL",
    from_level: 1,
    to_level: 4,
    plan: "Take an advanced PostgreSQL course and implement stored procedures and triggers.",
    resources: "https://www.udemy.com/course/sql-and-postgresql/",
  },
  {
    skill_id: 9,
    skill_name: "PostgreSQL",
    from_level: 2,
    to_level: 3,
    plan: "Design a normalized schema and write complex queries using subqueries and CTEs.",
    resources: "https://www.postgresql.org/docs/current/queries-with.html",
  },
  {
    skill_id: 9,
    skill_name: "PostgreSQL",
    from_level: 2,
    to_level: 4,
    plan: "Implement indexing strategies and analyze query performance using EXPLAIN.",
    resources: "https://www.postgresql.org/docs/current/using-explain.html",
  },
  {
    skill_id: 9,
    skill_name: "PostgreSQL",
    from_level: 3,
    to_level: 4,
    plan: "Contribute to PostgreSQL extensions or tools and write a performance guide.",
    resources: "https://wiki.postgresql.org/wiki/Performance_Optimization",
  },
  {
    skill_id: 10,
    skill_name: "Python",
    from_level: 1,
    to_level: 2,
    plan: "Start with Python basics on W3Schools and write scripts for simple tasks.",
    resources: "https://www.w3schools.com/python/",
  },
  {
    skill_id: 10,
    skill_name: "Python",
    from_level: 1,
    to_level: 3,
    plan: "Complete the Python course on freeCodeCamp and build a CLI tool or web scraper.",
    resources:
      "https://www.freecodecamp.org/news/learn-python-basics-in-5-hours/",
  },
  {
    skill_id: 10,
    skill_name: "Python",
    from_level: 1,
    to_level: 4,
    plan: "Take an advanced Python course and build a web app using Flask or Django.",
    resources: "https://www.udemy.com/course/complete-python-bootcamp/",
  },
  {
    skill_id: 10,
    skill_name: "Python",
    from_level: 2,
    to_level: 3,
    plan: "Write object-oriented programs and explore modules like requests and pandas.",
    resources: "https://realpython.com/",
  },
  {
    skill_id: 10,
    skill_name: "Python",
    from_level: 2,
    to_level: 4,
    plan: "Build a data analysis or automation project and explore concurrency in Python.",
    resources: "https://docs.python.org/3/library/asyncio.html",
  },

  {
    skill_id: 10,
    skill_name: "Python",
    from_level: 3,
    to_level: 4,
    plan: "Contribute to a Python open-source project on GitHub, then write a technical blog or tutorial explaining advanced Python concepts like decorators, generators, or metaclasses.",
    resources: "https://github.com/python",
  },

  {
    skill_id: 11,
    skill_name: "Django",
    from_level: 1,
    to_level: 2,
    plan: "Start with the official Django tutorial to build a basic blog app and understand the project structure.",
    resources: "https://docs.djangoproject.com/en/stable/intro/tutorial01/",
  },
  {
    skill_id: 11,
    skill_name: "Django",
    from_level: 1,
    to_level: 3,
    plan: "Complete the Django for Beginners book or course and build a multi-page site with forms and models.",
    resources: "https://djangoforbeginners.com/",
  },
  {
    skill_id: 11,
    skill_name: "Django",
    from_level: 1,
    to_level: 4,
    plan: "Take an advanced Django course and implement authentication, REST APIs, and deployment.",
    resources:
      "https://www.udemy.com/course/python-and-django-full-stack-web-developer-bootcamp/",
  },
  {
    skill_id: 11,
    skill_name: "Django",
    from_level: 2,
    to_level: 3,
    plan: "Build a Django app with class-based views and custom user models, then test it using Django’s test framework.",
    resources:
      "https://learndjango.com/tutorials/django-login-and-logout-tutorial",
  },
  {
    skill_id: 11,
    skill_name: "Django",
    from_level: 2,
    to_level: 4,
    plan: "Create a production-ready Django app with Docker and CI/CD, then deploy it to Heroku or AWS.",
    resources:
      "https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/",
  },
  {
    skill_id: 11,
    skill_name: "Django",
    from_level: 3,
    to_level: 4,
    plan: "Contribute to Django packages or plugins and write a blog on Django performance optimization.",
    resources: "https://github.com/django/django",
  },
  {
    skill_id: 12,
    skill_name: "REST API",
    from_level: 1,
    to_level: 2,
    plan: "Learn the basics of REST architecture and HTTP methods, then build a simple API using Flask or Express.",
    resources: "https://restfulapi.net/",
  },
  {
    skill_id: 12,
    skill_name: "REST API",
    from_level: 1,
    to_level: 3,
    plan: "Build a CRUD API with authentication and error handling, then document it using Swagger.",
    resources: "https://swagger.io/docs/specification/about/",
  },
  {
    skill_id: 12,
    skill_name: "REST API",
    from_level: 1,
    to_level: 4,
    plan: "Take an advanced REST API course and implement versioning, rate limiting, and caching.",
    resources:
      "https://www.udemy.com/course/rest-api-design-the-complete-guide/",
  },
  {
    skill_id: 12,
    skill_name: "REST API",
    from_level: 2,
    to_level: 3,
    plan: "Refactor your API to follow best practices like HATEOAS and use Postman for testing.",
    resources: "https://www.postman.com/",
  },
  {
    skill_id: 12,
    skill_name: "REST API",
    from_level: 2,
    to_level: 4,
    plan: "Implement API gateways and monitoring tools like Prometheus or New Relic.",
    resources: "https://www.nginx.com/learn/api-gateway/",
  },
  {
    skill_id: 12,
    skill_name: "REST API",
    from_level: 3,
    to_level: 4,
    plan: "Contribute to open-source API projects and write a guide on REST API security.",
    resources: "https://github.com/public-apis/public-apis",
  },
  {
    skill_id: 13,
    skill_name: "Unit Testing",
    from_level: 1,
    to_level: 2,
    plan: "Learn the basics of unit testing in your language of choice and write tests for simple functions.",
    resources: "https://realpython.com/python-testing/",
  },
  {
    skill_id: 13,
    skill_name: "Unit Testing",
    from_level: 1,
    to_level: 3,
    plan: "Write tests for modules and classes using a testing framework like PyTest or JUnit.",
    resources: "https://docs.pytest.org/en/stable/",
  },
  {
    skill_id: 13,
    skill_name: "Unit Testing",
    from_level: 1,
    to_level: 4,
    plan: "Take a course on test-driven development and integrate testing into your CI/CD pipeline.",
    resources: "https://www.udemy.com/course/tdd-django/",
  },
  {
    skill_id: 13,
    skill_name: "Unit Testing",
    from_level: 2,
    to_level: 3,
    plan: "Refactor your codebase to improve test coverage and use mocking for external dependencies.",
    resources: "https://docs.python.org/3/library/unittest.mock.html",
  },
  {
    skill_id: 13,
    skill_name: "Unit Testing",
    from_level: 2,
    to_level: 4,
    plan: "Implement parameterized tests and test edge cases, then measure coverage with tools like coverage.py.",
    resources: "https://coverage.readthedocs.io/",
  },
  {
    skill_id: 13,
    skill_name: "Unit Testing",
    from_level: 3,
    to_level: 4,
    plan: "Contribute to testing libraries or write a blog on testing strategies for large applications.",
    resources: "https://github.com/pytest-dev/pytest",
  },
  {
    skill_id: 14,
    skill_name: "Selenium",
    from_level: 1,
    to_level: 2,
    plan: "Install Selenium and write scripts to automate browser actions like clicking and form submission.",
    resources: "https://www.selenium.dev/documentation/",
  },
  {
    skill_id: 14,
    skill_name: "Selenium",
    from_level: 1,
    to_level: 3,
    plan: "Build a test suite for a web app and use locators, waits, and assertions effectively.",
    resources: "https://www.guru99.com/selenium-tutorial.html",
  },
  {
    skill_id: 14,
    skill_name: "Selenium",
    from_level: 1,
    to_level: 4,
    plan: "Take an advanced Selenium course and integrate tests with CI tools like Jenkins.",
    resources:
      "https://www.udemy.com/course/selenium-real-time-examplesinterview-questions/",
  },
  {
    skill_id: 14,
    skill_name: "Selenium",
    from_level: 2,
    to_level: 3,
    plan: "Use Selenium Grid for parallel testing and explore headless browser testing.",
    resources: "https://www.selenium.dev/documentation/grid/",
  },
  {
    skill_id: 14,
    skill_name: "Selenium",
    from_level: 2,
    to_level: 4,
    plan: "Automate complex workflows and integrate with reporting tools like Allure.",
    resources: "https://docs.qameta.io/allure/",
  },
  {
    skill_id: 14,
    skill_name: "Selenium",
    from_level: 3,
    to_level: 4,
    plan: "Contribute to Selenium plugins or write a guide on best practices for test automation.",
    resources: "https://github.com/SeleniumHQ/selenium",
  },

  {
    skill_id: 15,
    skill_name: "Jest",
    from_level: 1,
    to_level: 2,
    plan: "Install Jest in a JavaScript project and write basic test cases using matchers like `toBe` and `toEqual` to test simple functions.",
    resources: "https://jestjs.io/docs/getting-started",
  },
  {
    skill_id: 15,
    skill_name: "Jest",
    from_level: 1,
    to_level: 3,
    plan: "Use Jest with React Testing Library to test component rendering, props, and user interactions like clicks and form submissions.",
    resources: "https://testing-library.com/docs/react-testing-library/intro/",
  },
  {
    skill_id: 15,
    skill_name: "Jest",
    from_level: 1,
    to_level: 4,
    plan: "Take an advanced Jest course and implement snapshot testing, async testing with `async/await`, and mock API calls.",
    resources: "https://www.udemy.com/course/react-testing-library/",
  },
  {
    skill_id: 15,
    skill_name: "Jest",
    from_level: 2,
    to_level: 3,
    plan: "Refactor your tests to use mocks and spies for external dependencies, and test edge cases and error handling scenarios.",
    resources: "https://jestjs.io/docs/mock-functions",
  },
  {
    skill_id: 15,
    skill_name: "Jest",
    from_level: 2,
    to_level: 4,
    plan: "Integrate Jest into your CI/CD pipeline, configure test coverage thresholds, and use `jest.config.js` for custom setups.",
    resources: "https://jestjs.io/docs/code-coverage",
  },
  {
    skill_id: 15,
    skill_name: "Jest",
    from_level: 3,
    to_level: 4,
    plan: "Contribute to Jest plugins or testing libraries, and write a blog post or tutorial on advanced testing strategies in large-scale applications.",
    resources: "https://github.com/jest-community",
  },
  
  {
    skill_id: 16,
    skill_name: "Cypress",
    from_level: 1,
    to_level: 2,
    plan: "Install Cypress and write your first test to check if a webpage loads correctly and contains expected elements.",
    resources: "https://docs.cypress.io/guides/getting-started/writing-your-first-test"
  },
  {
    skill_id: 16,
    skill_name: "Cypress",
    from_level: 1,
    to_level: 3,
    plan: "Build a test suite for a web app using Cypress commands, assertions, and custom commands.",
    resources: "https://docs.cypress.io/guides/core-concepts/introduction-to-cypress"
  },
  {
    skill_id: 16,
    skill_name: "Cypress",
    from_level: 1,
    to_level: 4,
    plan: "Take an advanced Cypress course and integrate tests into a CI/CD pipeline using GitHub Actions or Jenkins.",
    resources: "https://www.udemy.com/course/cypress-tutorial/"
  },
  {
    skill_id: 16,
    skill_name: "Cypress",
    from_level: 2,
    to_level: 3,
    plan: "Use fixtures, intercept network requests, and test dynamic content with Cypress.",
    resources: "https://docs.cypress.io/guides/guides/network-requests"
  },
  {
    skill_id: 16,
    skill_name: "Cypress",
    from_level: 2,
    to_level: 4,
    plan: "Create reusable test components and integrate visual testing tools like Percy.",
    resources: "https://docs.percy.io/docs/cypress"
  },
  {
    skill_id: 16,
    skill_name: "Cypress",
    from_level: 3,
    to_level: 4,
    plan: "Contribute to Cypress plugins or write a guide on best practices for end-to-end testing.",
    resources: "https://github.com/cypress-io/cypress"
  },
  {
    skill_id: 17,
    skill_name: "Recruitment",
    from_level: 1,
    to_level: 2,
    plan: "Learn how to write effective job descriptions and post them on job boards like LinkedIn or Indeed.",
    resources: "https://business.linkedin.com/talent-solutions/resources/talent-engagement/job-descriptions"
  },
  {
    skill_id: 17,
    skill_name: "Recruitment",
    from_level: 1,
    to_level: 3,
    plan: "Study candidate screening techniques and practice conducting structured interviews.",
    resources: "https://www.indeed.com/hire/c/info/structured-interview"
  },
  {
    skill_id: 17,
    skill_name: "Recruitment",
    from_level: 1,
    to_level: 4,
    plan: "Take a recruitment strategy course and implement an applicant tracking system (ATS).",
    resources: "https://www.coursera.org/learn/recruiting-hiring-onboarding-employees"
  },
  {
    skill_id: 17,
    skill_name: "Recruitment",
    from_level: 2,
    to_level: 3,
    plan: "Use behavioral interview techniques and evaluate candidates using scorecards.",
    resources: "https://resources.workable.com/tutorial/behavioral-interview-questions"
  },
  {
    skill_id: 17,
    skill_name: "Recruitment",
    from_level: 2,
    to_level: 4,
    plan: "Develop a recruitment funnel and analyze hiring metrics to improve efficiency.",
    resources: "https://harver.com/blog/recruitment-funnel/"
  },
  {
    skill_id: 17,
    skill_name: "Recruitment",
    from_level: 3,
    to_level: 4,
    plan: "Contribute to HR communities and publish insights on modern recruitment trends.",
    resources: "https://www.shrm.org/"
  },
  {
    skill_id: 18,
    skill_name: "Employee Engagement",
    from_level: 1,
    to_level: 2,
    plan: "Understand the basics of employee engagement and conduct a simple pulse survey.",
    resources: "https://www.gallup.com/workplace/285674/improve-employee-engagement-workplace.aspx"
  },
  {
    skill_id: 18,
    skill_name: "Employee Engagement",
    from_level: 1,
    to_level: 3,
    plan: "Implement regular feedback sessions and recognition programs to boost morale.",
    resources: "https://www.officevibe.com/guide/employee-engagement"
  },
  {
    skill_id: 18,
    skill_name: "Employee Engagement",
    from_level: 1,
    to_level: 4,
    plan: "Take a leadership course focused on engagement and design a long-term engagement strategy.",
    resources: "https://www.coursera.org/learn/leadership-engagement"
  },
  {
    skill_id: 18,
    skill_name: "Employee Engagement",
    from_level: 2,
    to_level: 3,
    plan: "Analyze survey results and create action plans to address engagement gaps.",
    resources: "https://www.quantumworkplace.com/future-of-work/employee-engagement-action-plan"
  },
  {
    skill_id: 18,
    skill_name: "Employee Engagement",
    from_level: 2,
    to_level: 4,
    plan: "Use analytics tools to track engagement trends and present findings to leadership.",
    resources: "https://www.tinypulse.com/blog/employee-engagement-metrics"
  },
  {
    skill_id: 18,
    skill_name: "Employee Engagement",
    from_level: 3,
    to_level: 4,
    plan: "Contribute to HR forums and publish a case study on successful engagement initiatives.",
    resources: "https://www.hrexchangenetwork.com/"
  },
  {
    skill_id: 19,
    skill_name: "Payroll Management",
    from_level: 1,
    to_level: 2,
    plan: "Learn the basics of payroll processing and understand statutory deductions and compliance.",
    resources: "https://www.adp.com/resources/articles-and-insights/articles/p/payroll-101.aspx"
  },
  {
    skill_id: 19,
    skill_name: "Payroll Management",
    from_level: 1,
    to_level: 3,
    plan: "Use payroll software to process salaries and generate payslips and tax reports.",
    resources: "https://quickbooks.intuit.com/payroll/"
  },
  {
    skill_id: 19,
    skill_name: "Payroll Management",
    from_level: 1,
    to_level: 4,
    plan: "Take a payroll certification course and implement automated payroll systems.",
    resources: "https://www.udemy.com/course/payroll-management-system/"
  },
  {
    skill_id: 19,
    skill_name: "Payroll Management",
    from_level: 2,
    to_level: 3,
    plan: "Handle payroll for multiple departments and ensure compliance with labor laws.",
    resources: "https://www.shrm.org/resourcesandtools/hr-topics/compensation/pages/default.aspx"
  },
  {
    skill_id: 19,
    skill_name: "Payroll Management",
    from_level: 2,
    to_level: 4,
    plan: "Audit payroll processes and prepare for external compliance checks.",
    resources: "https://www.adp.com/resources/articles-and-insights/articles/a/audit-your-payroll-process.aspx"
  },
  {
    skill_id: 19,
    skill_name: "Payroll Management",
    from_level: 3,
    to_level: 4,
    plan: "Contribute to payroll forums and write a guide on best practices for payroll automation.",
    resources: "https://www.americanpayroll.org/"
  },
 
  {
    skill_id: 20,
    skill_name: "Conflict Resolution",
    from_level: 1,
    to_level: 2,
    plan: "Learn the basics of workplace conflict, including common causes and types, and practice active listening techniques to understand different perspectives.",
    resources: "https://www.mindtools.com/ajrnl5a/conflict-resolution"
  },
  {
    skill_id: 20,
    skill_name: "Conflict Resolution",
    from_level: 1,
    to_level: 3,
    plan: "Study conflict resolution models such as the Interest-Based Relational approach and role-play scenarios to practice mediation and de-escalation.",
    resources: "https://www.coursera.org/learn/conflict-resolution-skills"
  },
  {
    skill_id: 20,
    skill_name: "Conflict Resolution",
    from_level: 1,
    to_level: 4,
    plan: "Take a professional certification in conflict management and lead a resolution workshop within your organization to apply your skills in real settings.",
    resources: "https://www.udemy.com/course/conflict-management-with-emotional-intelligence/"
  },
  {
    skill_id: 20,
    skill_name: "Conflict Resolution",
    from_level: 2,
    to_level: 3,
    plan: "Apply structured resolution frameworks like the Thomas-Kilmann model in real workplace cases and document outcomes for reflection.",
    resources: "https://kilmanndiagnostics.com/overview-thomas-kilmann-conflict-mode-instrument-tki/"
  },
  {
    skill_id: 20,
    skill_name: "Conflict Resolution",
    from_level: 2,
    to_level: 4,
    plan: "Develop a conflict resolution policy for your team or department, incorporating feedback from HR and leadership.",
    resources: "https://www.shrm.org/resourcesandtools/hr-topics/employee-relations/pages/conflict-resolution.aspx"
  },
  {
    skill_id: 20,
    skill_name: "Conflict Resolution",
    from_level: 3,
    to_level: 4,
    plan: "Contribute to HR forums or write a case study on a successful conflict resolution initiative, highlighting techniques and outcomes.",
    resources: "https://www.hrexchangenetwork.com/hr-management/articles/5-conflict-resolution-strategies-we-all-use"
  }

];

// module.exports = {skillUpgradeData};
